{% set name = "pyxDamerauLevenshtein" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/gfairchild/pyxDamerauLevenshtein/archive/v{{ version }}.tar.gz
  sha256: e2bd561d97dc5441772379826d665fa8b2bffc2e0180da03b2b29b48f38b97d5

build:
  number: 2
  script: |
    {{ PYTHON }} -m cython pyxdameraulevenshtein/*.pyx
    {{ PYTHON }} -m pip install . -vv --no-deps
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyxdameraulevenshtein

about:
  home: https://github.com/gfairchild/pyxDamerauLevenshtein
  license: BSD-3-Clause
  license_file: LICENSE
  summary: High performance Damerau-Levenshtein (DL) edit distance algorithm for Python.
  description: |
    pyxDamerauLevenshtein implements the Damerau-Levenshtein (DL) edit distance
    algorithm for Python in Cython for high performance.
  doc_url: https://github.com/gfairchild/pyxDamerauLevenshtein
  dev_url: https://github.com/gfairchild/pyxDamerauLevenshtein

extra:
  recipe-maintainers:
    - CJ-Wright
    - mrakitin
