{% set name = "pyxDamerauLevenshtein" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/gfairchild/pyxDamerauLevenshtein/archive/v{{ version }}.tar.gz
  sha256: 6a2a2ab90f31744f92c59a69344d6aa489565fdff062d9dc3ceb1d9d1a8e5fb5

build:
  number: 1
  script: |
    {{ PYTHON }} -m pip install . -vv --no-deps  --no-build-isolation
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - pyxdameraulevenshtein

about:
  home: https://github.com/gfairchild/pyxDamerauLevenshtein
  license: BSD-3-Clause
  license_file: LICENSE
  summary: High performance Damerau-Levenshtein (DL) edit distance algorithm for Python.
  description: |
    pyxDamerauLevenshtein implements the Damerau-Levenshtein (DL) edit distance
    algorithm for Python in Cython for high performance.
  doc_url: https://github.com/gfairchild/pyxDamerauLevenshtein
  dev_url: https://github.com/gfairchild/pyxDamerauLevenshtein

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - CJ-Wright
    - mrakitin
