{% set name = "pyxDamerauLevenshtein" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gfairchild/pyxDamerauLevenshtein/archive/v{{ version }}.tar.gz
  sha256: 56d879e080d2fc699dc43e10ae6302f6fc30899f963bc13cb3a695c5c1e5d2a8

build:
  number: 2
  script: |
    {{ PYTHON }} -m pip install . -vv --no-deps  --no-build-isolation
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - pyxdameraulevenshtein

about:
  home: https://github.com/gfairchild/pyxDamerauLevenshtein
  license: BSD-3-Clause
  license_file: LICENSE
  summary: High performance Damerau-Levenshtein (DL) edit distance algorithm for Python.
  description: |
    pyxDamerauLevenshtein implements the Damerau-Levenshtein (DL) edit distance
    algorithm for Python in Cython for high performance.
  doc_url: https://github.com/gfairchild/pyxDamerauLevenshtein
  dev_url: https://github.com/gfairchild/pyxDamerauLevenshtein

extra:
  recipe-maintainers:
    - CJ-Wright
    - mrakitin
