appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: Vacdo0DweLL4d+7J2+vTLUXQRhAIiCSNz40MkCHsZt2Rt2Lyi2K76qPztvgSl8ox6E5doXDnLRmysNov/B+XLao4qCHH01OJraCbXWdlX7Z/QPL8lGxF3SZc7ep7mIoXt1ntIKqdlEd3tHTf9LYN93hNQCEdTa6wH4Vyxd5SfnHhnqp0mU4eM0XcPV+DgeMRP37wxtB41+P4rDUG+f6H++jSEFiZtW+n9Nr9iKnjg/krTImQDZ9Qz1qOGL+IdIKHBxjpB/ioTCjCviEtlcc0sxG56NI/+Z5MbJIyc/TeZzXE3//QiZ91KbpbMG7kmXp7k0VFx381K1ZG7vlZN2zIrOdnXdFoRrv1CTRwRTDBgw3Xrq4o5mO4C6/5XvhT/rQPIeo060dyBI2AzJK+GGYDfFzqkYe8+G3sP6pt5I85xH0acIIEhCkVrN6L8epeJEeltfdSmHsw67eJJihv2HgqjlFyyqKvWGZV1QJJ4KIQWFaD9eLUe2rimVOVQ25YFlzcfk5hNNTKEpdAdxv2q6VKCJcP5WO4WR7B7u4cSr4V/CM0OYnPRdTXdlH7/GPLJ7uYAZw6HVnLUDJIX5CE+QqWCKMqyliZWT9MLSpQRrOInHGk5v10a4mP/5YSaxDV04urQHvqrrHDTNfoo8pnT2sFj4qV6X6c78K7PFSkI13bhW4=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
